### ISSUE TITLE
Assignment consistency

### ISSUE THREAD

**Issue by Dasonk** [jalapic/RPackage#1]
I think one think code maintainers should strive for is a consistent coding convention.  It looks like the example R code switches between using `<-` and `=` frequently. It might not be a bad idea to try to use a consistent convention for assignment (and in general but this was the most obvious piece to me).  Having students learn that early on and sticking with it is much easier than having them realize later that they want to be consistent and having to update code and get that ingrained into them at that point.

**Comment by jalapic** [comment]
yes, I agree.  In the live coding I actually noticed this and corrected it.  I will fix them for students.
